//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MockProject.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTPHIEUNHAPXUATKHO
    {
        public int NhapXuatKhoID { get; set; }
        public int SanPhamID { get; set; }
        public Nullable<decimal> SoLuong { get; set; }
        public Nullable<decimal> DonGia { get; set; }
    
        public virtual NHAPXUATKHO NHAPXUATKHO { get; set; }
        public virtual SANPHAM SANPHAM { get; set; }
    }
}
