//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MockProject.DataBase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GST_MockProjectEntities : DbContext
    {
        public GST_MockProjectEntities()
            : base("name=GST_MockProjectEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BILL> BILLs { get; set; }
        public virtual DbSet<BILL_DETAIL> BILL_DETAIL { get; set; }
        public virtual DbSet<PRODUCT> PRODUCTs { get; set; }
        public virtual DbSet<PRODUCT_TYPE> PRODUCT_TYPE { get; set; }
        public virtual DbSet<RETURN_BILL> RETURN_BILL { get; set; }
        public virtual DbSet<RETURNBILL_DETAIL> RETURNBILL_DETAIL { get; set; }
        public virtual DbSet<USER> USERs { get; set; }
        public virtual DbSet<USER_PERMISSION> USER_PERMISSION { get; set; }
        public virtual DbSet<WAREHOUSE> WAREHOUSEs { get; set; }
        public virtual DbSet<WAREHOUSE_DETAIL> WAREHOUSE_DETAIL { get; set; }
        public virtual DbSet<WAREHOUSE_TRANSACTION> WAREHOUSE_TRANSACTION { get; set; }
        public virtual DbSet<WAREHOUSETRANSACTION_DETAIL> WAREHOUSETRANSACTION_DETAIL { get; set; }
        public virtual DbSet<NOTIFY> NOTIFies { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
