//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MockProject.DataBase
{
    using System;
    
    public enum LoaiGioiTinh : int
    {
        Nam = 0,
        Nu = 1,
        ChuaXacDinh = 2,
    }
}
