//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MockProject.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class SANPHAM
    {
        public int Id { get; set; }
        public string TenSanpham { get; set; }
        public Nullable<decimal> Giaban { get; set; }
        public Nullable<int> Soluongton { get; set; }
        public string Donvitinh { get; set; }
        public string Image { get; set; }
        public Nullable<int> LoaiSanphamID { get; set; }
    
        public virtual LOAISANPHAM LOAISANPHAM { get; set; }
    }
}
