//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MockProject.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class SANPHAM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SANPHAM()
        {
            this.CTKHOes = new HashSet<CTKHO>();
            this.CTPHIEUTRAHANGs = new HashSet<CTPHIEUTRAHANG>();
            this.CTPHIEUNHAPXUATKHOes = new HashSet<CTPHIEUNHAPXUATKHO>();
            this.CTHDs = new HashSet<CTHD>();
        }
    
        public int ID { get; set; }
        public Nullable<int> LoaiSanPhamID { get; set; }
        public string TenSP { get; set; }
        public string HinhSP { get; set; }
        public string MoTa { get; set; }
        public Nullable<decimal> GiaBan { get; set; }
        public Nullable<decimal> SoLuongTon { get; set; }
        public string DonViTinh { get; set; }
        public Nullable<bool> TrangThai { get; set; }
    
        public virtual LOAISANPHAM LOAISANPHAM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTKHO> CTKHOes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTPHIEUTRAHANG> CTPHIEUTRAHANGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTPHIEUNHAPXUATKHO> CTPHIEUNHAPXUATKHOes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTHD> CTHDs { get; set; }
    }
}
