//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MockProject.DataBase
{
    using System;
    
    public enum TrangThaiNhanVien : int
    {
        DangLamViec = 0,
        NghiViec = 1,
        NghiPhep = 2,
        CongTac = 3,
    }
}
