//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MockProject.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_PERMISSION
    {
        public int User_ID { get; set; }
        public int Permisstion_ID { get; set; }
    
        public virtual USER USER { get; set; }
    }
}
