//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MockProject.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class WAREHOUSE_TRANSACTION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WAREHOUSE_TRANSACTION()
        {
            this.WAREHOUSETRANSACTION_DETAIL = new HashSet<WAREHOUSETRANSACTION_DETAIL>();
        }
    
        public int ID { get; set; }
        public int Warehouse_ID { get; set; }
        public Nullable<WarehouseTransaction_Type> Type { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> UpdateBy { get; set; }
    
        public virtual USER USER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WAREHOUSETRANSACTION_DETAIL> WAREHOUSETRANSACTION_DETAIL { get; set; }
        public virtual USER USER1 { get; set; }
        public virtual WAREHOUSE WAREHOUSE { get; set; }
    }
}
