//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MockProject.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class WAREHOUSE_DETAIL
    {
        public int Warehouse_ID { get; set; }
        public int Product_ID { get; set; }
        public Nullable<decimal> Quantity { get; set; }
    
        public virtual PRODUCT PRODUCT { get; set; }
        public virtual WAREHOUSE WAREHOUSE { get; set; }
    }
}
