//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MockProject.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class WAREHOUSE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WAREHOUSE()
        {
            this.WAREHOUSE_DETAIL = new HashSet<WAREHOUSE_DETAIL>();
            this.WAREHOUSE_TRANSACTION = new HashSet<WAREHOUSE_TRANSACTION>();
        }
    
        public int ID { get; set; }
        public string WarehouseName { get; set; }
        public string Address { get; set; }
        public Nullable<Warehouse_Status> Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WAREHOUSE_DETAIL> WAREHOUSE_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WAREHOUSE_TRANSACTION> WAREHOUSE_TRANSACTION { get; set; }
    }
}
