//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MockProject.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EnumText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EnumText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MockProject.Resources.EnumText", typeof(EnumText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa xác định.
        /// </summary>
        public static string LoaiGioiTinh_ChuaXacDinh {
            get {
                return ResourceManager.GetString("LoaiGioiTinh.ChuaXacDinh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nam.
        /// </summary>
        public static string LoaiGioiTinh_Nam {
            get {
                return ResourceManager.GetString("LoaiGioiTinh.Nam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nữ.
        /// </summary>
        public static string LoaiGioiTinh_Nu {
            get {
                return ResourceManager.GetString("LoaiGioiTinh.Nu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang dùng.
        /// </summary>
        public static string TrangThaiLoaiSanPham_Dung {
            get {
                return ResourceManager.GetString("TrangThaiLoaiSanPham.Dung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không dùng.
        /// </summary>
        public static string TrangThaiLoaiSanPham_KhongDung {
            get {
                return ResourceManager.GetString("TrangThaiLoaiSanPham.KhongDung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Công tác.
        /// </summary>
        public static string TrangThaiNhanVien_CongTac {
            get {
                return ResourceManager.GetString("TrangThaiNhanVien.CongTac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang làm việc.
        /// </summary>
        public static string TrangThaiNhanVien_DangLamViec {
            get {
                return ResourceManager.GetString("TrangThaiNhanVien.DangLamViec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nghĩ phép.
        /// </summary>
        public static string TrangThaiNhanVien_NghiPhep {
            get {
                return ResourceManager.GetString("TrangThaiNhanVien.NghiPhep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nghĩ việc.
        /// </summary>
        public static string TrangThaiNhanVien_NghiViec {
            get {
                return ResourceManager.GetString("TrangThaiNhanVien.NghiViec", resourceCulture);
            }
        }
    }
}
